// Run against HTML generated by test_section_width.py, using the real assets.
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const [cli, jquery, fixtures] = process.argv.slice(2);
const root = path.resolve(__dirname, '../..');
const assets = Object.fromEntries([
  'data-stories-edit', 'data-stories-visuals-edit', 'data-stories-sequence',
  'story-playback', 'data-stories-visuals', 'data-stories-storymap', 'story-editor-core', 'terria-tabs-display'
].map(name => ['/js/' + name + '.js', path.join(root, 'public/js', name + '.js')]));
for (const name of ['data-stories-edit', 'data-stories-visuals', 'data-stories-storymap'])
  assets['/css/' + name + '.css'] = path.join(root, 'public/css', name + '.css');
assets['/css/data-stories.css'] = path.join(root, 'theme/public/css/data-stories.css');
assets['/jquery.js'] = path.resolve(jquery);
assets['/quill.js'] = path.join(root, 'assets/vendor/quill/quill.min.js');
const markup = JSON.parse(fs.readFileSync(fixtures, 'utf8'));
const pages = {};
for (const [mode, html] of Object.entries(markup)) {
  pages[mode] = path.join(path.dirname(path.resolve(fixtures)), mode + '.html');
  fs.writeFileSync(pages[mode], '<style>body{margin:0} *,*::before,*::after{box-sizing:border-box}</style><script src="/jquery.js"></script>' + html);
}
function run(...args) {
  return execFileSync('bash', [cli, '-s=section-width-tests', ...args], {encoding: 'utf8', maxBuffer: 4 * 1024 * 1024});
}

async function check(page, assets, pages) {
  const errors = [];
  const measurements = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('https://stories.test/**', async route => {
    const pathname = new URL(route.request().url()).pathname;
    if (assets[pathname]) return route.fulfill({path: assets[pathname]});
    const mode = pathname.slice(1);
    return pages[mode] ? route.fulfill({contentType: 'text/html', path: pages[mode]}) : route.fulfill({body: ''});
  });
  for (const mode of ['classic', 'storymap', 'slides']) {
    await page.goto('https://stories.test/' + mode);
    if (mode !== 'classic') await page.addStyleTag({path: assets['/css/data-stories-storymap.css']});
    for (const width of [1920, 1440, 768, 390]) {
      await page.setViewportSize({width, height: 900});
      // The existing module theme animates all properties for 300 ms.
      await page.waitForTimeout(350);
      if (mode === 'slides') await page.locator('.storymap-slide-controls select').selectOption('0');
      for (let index = 0; index < 4; index++) {
        if (mode === 'slides') await page.locator('.storymap-slide-controls select').selectOption(String(index * 2));
        const section = page.locator(mode === 'classic' ? '#section-width-' + index : '#scene-width-' + index);
        const body = mode === 'classic' ? section : section.locator('.storymap-card-body');
        const metrics = await body.evaluate(el => ({
          width: el.getBoundingClientRect().width, x: el.getBoundingClientRect().x,
          text: el.querySelector('.section-content p').getBoundingClientRect().width,
          media: el.querySelector('iframe').getBoundingClientRect().width,
          viewport: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth
        }));
        if (mode === 'slides') {
          await page.locator('.storymap-slide-controls select').selectOption(String(index * 2 + 1));
          metrics.media = await section.locator('iframe').evaluate(el => el.getBoundingClientRect().width);
        }
        const expected = width <= 768 || index === 1 ? metrics.viewport : index === 2 ? metrics.viewport * .8 : 900;
        if (index > 0 && (Math.abs(metrics.width - expected) > 1 || Math.abs(metrics.x - (metrics.viewport - expected) / 2) > 1))
          throw Error('Incorrect centered width: ' + JSON.stringify({mode, index, width, expected, metrics}));
        if (index > 0 && metrics.text < expected - (width <= 768 ? 32 : 48) - 1)
          throw Error('Narrative still has a reading-column limit: ' + JSON.stringify({mode, index, width, metrics}));
        if (metrics.scroll > metrics.viewport + 1) throw Error('Horizontal overflow: ' + JSON.stringify({mode, index, width, metrics}));
        if (index > 0 && width > 768 && Math.abs(metrics.media - 600) > 1)
          throw Error('Custom media width lost: ' + JSON.stringify({mode, index, width, metrics}));
        measurements.push({mode, viewport: width, section: index, width: metrics.width});
      }
      if (mode === 'slides') {
        await page.getByRole('button', {name: 'Previous', exact: true}).click();
        await page.getByRole('button', {name: 'Previous', exact: true}).click();
        if (!await page.locator('#scene-width-2').isVisible()) throw Error('Previous failed');
        await page.getByRole('button', {name: 'Next', exact: true}).click();
        if (!await page.locator('#scene-width-3').isVisible()) throw Error('Next failed');
      }
    }
  }

  async function editor(saved) {
    await page.goto('https://stories.test/editor');
    if (saved) await page.locator('.section-blocks-metadata').evaluateAll((fields, values) => fields.forEach((field, i) => {field.value = JSON.stringify(values[i]);}), saved);
    await page.addStyleTag({path: assets['/css/data-stories-visuals.css']});
    for (const src of ['/quill.js', '/js/story-editor-core.js', '/js/data-stories-sequence.js', '/js/data-stories-visuals-edit.js', '/js/data-stories-edit.js'])
      await page.addScriptTag({path: assets[src]});
    await page.waitForFunction(() => document.querySelectorAll('.ql-editor').length === 4 &&
      [...document.querySelectorAll('.section-blocks-metadata')].every(el => JSON.parse(el.value)[0].width));
  }
  await page.setViewportSize({width: 1440, height: 900});
  await editor();
  const sections = page.locator('.content-section-editor');
  const custom = sections.nth(2);
  await custom.getByLabel('Width value', {exact: true}).fill('65');
  await custom.getByLabel('Width unit', {exact: true}).selectOption('%');
  await custom.locator('.move-section-up').click();
  const saved = await page.locator('.section-blocks-metadata').evaluateAll(fields => fields.map(el => JSON.parse(el.value)));
  if (saved[1][0].width.value !== 65 || saved[2][0].width.mode !== 'full') throw Error('Reordering lost widths');
  await editor(saved);
  const reloaded = await page.locator('.section-blocks-metadata').evaluateAll(fields => fields.map(el => JSON.parse(el.value)[0].width));
  if (JSON.stringify(reloaded) !== JSON.stringify(saved.map(blocks => blocks[0].width))) throw Error('Reload changed widths');
  const changed = sections.nth(1);
  for (const value of ['', '0', '-1', '101']) {
    await changed.getByLabel('Width value', {exact: true}).fill(value);
    if (await page.locator('form').evaluate(el => el.checkValidity())) throw Error('Invalid width accepted: ' + value);
  }
  await changed.getByLabel('Width value', {exact: true}).fill('80');
  if (!await page.locator('form').evaluate(el => el.checkValidity())) throw Error('Valid width rejected');
  for (const mode of ['storymap', 'slides', 'classic']) {
    await page.locator('#display_mode').selectOption(mode);
    if (await changed.getByLabel('Section width', {exact: true}).isDisabled()) throw Error('Narrative width disabled');
  }
  await changed.locator('.add-terria-block').click();
  await changed.locator('.terria-tab-url').fill('https://maps.test/#share=example');
  await changed.getByLabel('Section template', {exact: true}).selectOption('auto');
  await page.locator('#display_mode').selectOption('storymap');
  if (!await changed.getByLabel('Section width', {exact: true}).isDisabled()) throw Error('Split width should be disabled');
  await changed.getByLabel('Section template', {exact: true}).selectOption('full');
  if (await changed.getByLabel('Section width', {exact: true}).isDisabled() || await changed.getByLabel('Width value', {exact: true}).inputValue() !== '80')
    throw Error('Returning to narrative lost the custom width');
  if (errors.length) throw Error('Browser errors: ' + errors.join('; '));
  return {result: 'PASS: real templates in all modes, responsive widths, custom media, navigation, editor reload/reorder and validation', measurements};
}

try {
  run('open', 'about:blank');
  const result = run('run-code', `async page => (${check.toString()})(page, ${JSON.stringify(assets)}, ${JSON.stringify(pages)})`);
  if (!result.includes('PASS:')) throw Error(result);
  console.log(result.slice(0, result.indexOf('### Ran Playwright')));
} catch (error) {
  console.error(error.stdout || error.stderr || error.message.slice(0, 3000));
  process.exitCode = 1;
} finally { run('close'); }
